# Generated by Django 4.2.8 on 2024-01-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomobjectidentifiers',
            old_name='roomObject_id',
            new_name='id',
        ),
    ]
