# Generated by Django 4.2.8 on 2024-01-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_roomobject_id_roomobjectidentifiers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='theme',
        ),
    ]
