# Generated by Django 4.2.8 on 2024-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_operatorid_alter_roomobjectidentifiers_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomobjectidentifiers',
            old_name='IO_state',
            new_name='guest',
        ),
        migrations.AlterField(
            model_name='roomobjectidentifiers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
