# Generated by Django 4.2.8 on 2024-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_rename_io_state_roomobjectidentifiers_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasensorobjects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serialconfigurationobjecta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serialconfigurationobjectb',
            name='id',
        ),
        migrations.AddField(
            model_name='datasensorobjects',
            name='config_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='roomobjectidentifiers',
            name='config_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serialconfigurationobjecta',
            name='config_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='serialconfigurationobjectb',
            name='config_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
