# Generated by Django 4.2.8 on 2024-02-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_datasensorobjects_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialconfigurationobjectb',
            name='serial_port',
        ),
        migrations.AlterField(
            model_name='serialconfigurationobjecta',
            name='serial_port',
            field=models.CharField(blank=True, default='/dev/ttyUSB0', max_length=100),
        ),
    ]
