# Generated by Django 4.2.8 on 2024-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_serialconfigurationobjectb_serial_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialconfigurationobjecta',
            name='config_id',
            field=models.IntegerField(default=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serialconfigurationobjectb',
            name='config_id',
            field=models.IntegerField(default=8, primary_key=True, serialize=False),
        ),
    ]
